version: 1
formatters:
    simple:
        format: "%(asctime)s %(name)s %(levelname)s: %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
    stream_handler:
        class: logging.StreamHandler
        stream: ext://sys.stderr
        level: DEBUG
        formatter: simple
    file_handler:
        class: logging.FileHandler
        filename: ../../../logs/train.log
        level: DEBUG
        formatter: simple
loggers:
    train:
        level: DEBUG
        propagate: False
        handlers:
            - file_handler
            - stream_handler

    data:
        level: DEBUG
        propagate: False
        handlers:
            - file_handler
            - stream_handler

    predict:
        level: DEBUG
        propagate: False
        handlers:
            - file_handler
            - stream_handler

root:
    level: INFO
    handlers:
        - stream_handler
