log_config: configs/log_predict.yaml

model: models/model.pkl

transform_path:
  numerical: "models/numerical.pkl"
  categorical: "models/categorical.pkl"

features: configs/features/5cat_8num.yaml

data_path: data/raw/heart.csv
predict_path: outputs/predict.csv
