apiVersion: v1
kind: Pod
metadata:
  name: online-inference-res-probes
  labels:
    app: online-inference-res-probes
spec:
  containers:
    - image: andyst75/online_inference:v2
      name: online-inference-res-probes
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: 128Mi
          cpu: 500m
        limits:
          memory: 256Mi
          cpu: 800m
      startupProbe:
        httpGet:
          path: /health
          port: 8000
        failureThreshold: 1
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 10
