apiVersion: v1
kind: Pod
metadata:
  name: online-inference-res-probes
  labels:
    app: online-inference-res-probes
spec:

  containers:
    - image: andyst75/online_inference:v3
      name: online-inference-res-probes

      ports:
      - name: probe-port
        containerPort: 8000
        hostPort: 8000
        protocol: TCP

      resources:
        requests:
          memory: 128Mi
          cpu: 500m
        limits:
          memory: 256Mi
          cpu: 800m

      livenessProbe:
        httpGet:
          path: /healthz
          port: probe-port
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 5

      readinessProbe:
        httpGet:
          path: /healthz
          port: probe-port
        initialDelaySeconds: 20
        periodSeconds: 5
        failureThreshold: 5
